# Numpy 

### Numpy python programlama dilinin bazı numerik işlemlerde yetersiz kaldığı noktalarda ihtiyaçların giderilmesi için ortaya çıkmış kütüphanedir

* Numerical Python
* Bilimsel hesaplamalar için kullanılır
* Arraylar / çok boyutlu arraylar ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
* Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır.

In [28]:
a = [1,2,3,4]
b = [2,3,4,5]


In [31]:
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [1]:
import numpy as np

In [33]:
a = np.array([1,2,3,4])
b= np.array([2,3,4,5])
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [3]:
import numpy as np

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
a=np.array([1,2,3,4,5])

In [11]:
type(a)

numpy.ndarray

In [17]:
np.array([3.14,4,2,13],dtype="int")

array([ 3,  4,  2, 13])

In [19]:
# sıfırdan array oluşturma

In [23]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [35]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [37]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [39]:
np.random.normal(10,4,(3,4))

array([[14.75196746,  9.77016468,  6.81807396,  9.10761931],
       [ 8.77747285, 17.43871817, 10.90909336, 13.92922112],
       [ 9.85768793, 13.03360847, 17.9659091 , 16.16463835]])

In [41]:
# np.random.normal(10,4,(3,4)) ortalaması 10,standartSapması 4, ve 3' e 4 lük bir matris istediğimiz bir dağılım özelliği taşıyan arrayler oluşturabiliyoruz

In [43]:
np.random.randint(0,10,(3,3))

array([[1, 9, 4],
       [0, 1, 5],
       [1, 6, 2]])

# NUMPY ARRAY'IN ÖZELLİKLERİNE ULAŞMA

* ndim  : boyut sayısı
* shape : boyut bilgisi
* size  : toplam eleman sayısı
* dtype : array veri tipi

In [53]:
np.random.randint(10,size=10)

array([1, 1, 9, 9, 8, 8, 1, 2, 2, 5])

In [55]:
a=np.random.randint(10,size=10)

In [57]:
a.ndim #boyut sayısı

1

In [63]:
a.shape #boyut bilgisi (tek boyutlu ve içinde 10 eleman var)

(10,)

In [65]:
a.size  #toplam eleman sayısı

10

In [67]:
a.dtype # array veri tipi

dtype('int32')

In [69]:
b= np.random.randint(10,size=(3,5))

In [71]:
b.ndim

2

In [73]:
b.shape

(3, 5)

In [75]:
b.size

15

In [77]:
b.dtype

dtype('int32')

# YENİDEN ŞEKİLLENDİRME

In [82]:
np.arange(1,10) # elimdeki bu arrayden 3,3 lük yeni bir array oluşturmak istersem bu durumda (reshaping) fonksiyonu kullanılır

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* Neden böyle bir duruma ihtiyacım var yaptığımız çalışmada fonksiyonlarımızın veya döngülerimizin ürettiği çıktılar tek bir array formunda gerçekleşebiliyor bunları bazen tek boyuttan iki boyuta bazende iki boyuttan tek boyuta yeniden şekillendirme ihtiyacımız oluyor bu sebeple bu yapısal dönüşümle çözümlüyoruz.

In [85]:
np.arange(1,10).reshape((3,3)) # mevcut arrayi tek boyuttan iki boyuta yeniden şekillendiriyor 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
a=np.arange(1,10)

In [89]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a.ndim # tek boyutlu array "Vektör" dür

1

In [93]:
a.reshape((1,9)) # iki boyutlu "Matris" dir bir satır 9 sütundan oluşmuştur

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [95]:
b.ndim

2

# ARRAY BİRLEŞTİRME (CONCATENATION)

In [98]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [102]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [104]:
z=np.array([7,8,9])

In [106]:
np.concatenate([x,y,z]) # tek boyutlu dizileri birleştirdi

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a = np.array([[1,2,3],
              [4,5,6]])

In [114]:
np.concatenate([a,a]) # iki boyutlu dizileri birleştirdi hatta aynı diziyi çoğalttı

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [116]:
b=np.array([[7,8,9],[0,9,8]])

In [121]:
np.concatenate([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 9, 8]])

In [125]:
np.concatenate([a,b],axis=1)# sütun bazlı birleştirme gerçekleşti axis=0 default ve satır bazlı birleştirme

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 9, 8]])

# ARRAY AYIRMA (Splitting)

In [131]:
x=np.array([1,2,3,99,99,3,2,1])

In [133]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [135]:
a,b,c=np.split(x,[3,5])

In [137]:
a

array([1, 2, 3])

In [139]:
b

array([99, 99])

In [141]:
c

array([3, 2, 1])

In [143]:
# iki boyutlu ayırma işlemi

In [145]:
m=np.arange(16).reshape(4,4)

In [147]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [149]:
np.vsplit(m,[2]) # birinci parametre bölünecek array ikinci parametre index numarası 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [151]:
ust,alt=np.vsplit(m,[2])

In [153]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [155]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [157]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [165]:
sag,sol=np.hsplit(m,[2])

In [167]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [169]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# ARRAY SIRALAMA (Sorting)

In [173]:
v=np.array([2,1,4,3,5])

In [175]:
v

array([2, 1, 4, 3, 5])

In [178]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [180]:
v.sort()

In [182]:
v

array([1, 2, 3, 4, 5])

In [186]:
# iki boyutlu array sıralama

In [194]:
m=np.random.normal(20,5,(3,3))

In [196]:
m

array([[16.67850406, 17.80294077, 21.27293834],
       [ 6.09875931, 24.82506633, 22.04919964],
       [20.48686341, 20.59918645,  7.40000643]])

In [198]:
np.sort(m,axis=1) # satıra göre sıralama

array([[16.67850406, 17.80294077, 21.27293834],
       [ 6.09875931, 22.04919964, 24.82506633],
       [ 7.40000643, 20.48686341, 20.59918645]])

In [200]:
np.sort(m,axis=0) # sütüna göre sıralama

array([[ 6.09875931, 17.80294077,  7.40000643],
       [16.67850406, 20.59918645, 21.27293834],
       [20.48686341, 24.82506633, 22.04919964]])

# INDEX ILE ELEMANLARA ERIŞMEK (index)

In [203]:
a=np.random.randint(10,size=10)

In [205]:
a

array([2, 7, 8, 7, 1, 9, 7, 1, 6, 6])

In [207]:
a[0]

2

In [209]:
a[-1]

6

In [211]:
a[0]=100

In [213]:
a

array([100,   7,   8,   7,   1,   9,   7,   1,   6,   6])

In [217]:
m=np.random.randint(10,size=(3,5))

In [219]:
m

array([[0, 9, 3, 4, 5],
       [6, 1, 8, 2, 8],
       [9, 5, 6, 6, 4]])

In [221]:
m[0,0]

0

In [223]:
m[0,1]

9

In [227]:
m[1,4]=99

In [229]:
m

array([[ 0,  9,  3,  4,  5],
       [ 6,  1,  8,  2, 99],
       [ 9,  5,  6,  6,  4]])

In [231]:
m[1,4]=2.2

In [233]:
m

array([[0, 9, 3, 4, 5],
       [6, 1, 8, 2, 2],
       [9, 5, 6, 6, 4]])

# Slicing ile Elemanlara Erişmek (Array alt Kümesine Erişmek)

In [236]:
a=np.arange(20,30)

In [238]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [244]:
a[:] # aralıklı seçme işlemi ":" işaretinin solundaki index başlangıç sağındaki bitişi temsil ediyor

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [248]:
a[0:5]

array([20, 21, 22, 23, 24])

In [250]:
a[:3]

array([20, 21, 22])

In [252]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [260]:
a[1::2] # birinci elemandan başla ikişer ikişer atlayarak diziyi göster

array([21, 23, 25, 27, 29])

In [262]:
# iki boyutlu slice islemleri

In [266]:
m= np.random.randint(10,size=(5,5))

In [268]:
m

array([[1, 6, 4, 1, 4],
       [4, 9, 4, 3, 8],
       [4, 3, 3, 9, 4],
       [6, 9, 8, 7, 1],
       [8, 3, 1, 0, 0]])

In [272]:
m[:,0] # ":" solundaki satır sağındaki sütunu temsil ediyor bütün satırları seç ve 0 ıncı sütunu getir

array([1, 4, 4, 6, 8])

In [274]:
m[:,4]

array([4, 8, 4, 1, 0])

In [276]:
m[:,1]

array([6, 9, 3, 9, 3])

In [280]:
m

array([[1, 6, 4, 1, 4],
       [4, 9, 4, 3, 8],
       [4, 3, 3, 9, 4],
       [6, 9, 8, 7, 1],
       [8, 3, 1, 0, 0]])

In [282]:
m[0,:]

array([1, 6, 4, 1, 4])

In [285]:
m[0]

array([1, 6, 4, 1, 4])

In [287]:
m[1,:]

array([4, 9, 4, 3, 8])

In [291]:
m[0:2,0:3] # 0 dan 2 ye kadar satırları ve 0 dan 3 e kadar sütunları göster

array([[1, 6, 4],
       [4, 9, 4]])

In [296]:
m[::,:2]

array([[1, 6],
       [4, 9],
       [4, 3],
       [6, 9],
       [8, 3]])

In [300]:
m

array([[1, 6, 4, 1, 4],
       [4, 9, 4, 3, 8],
       [4, 3, 3, 9, 4],
       [6, 9, 8, 7, 1],
       [8, 3, 1, 0, 0]])

In [302]:
m[1:3,0:2]

array([[4, 9],
       [4, 3]])

# Alt Küme Üzerinde İşlem Yapmak

In [304]:
a= np.random.randint(10,size=(5,5))

In [306]:
a

array([[5, 1, 1, 8, 4],
       [9, 5, 9, 8, 1],
       [0, 3, 1, 1, 9],
       [0, 6, 0, 2, 9],
       [5, 1, 9, 6, 2]])

In [309]:
alt_a = a[0:3,0:2]

In [311]:
alt_a

array([[5, 1],
       [9, 5],
       [0, 3]])

In [317]:
alt_a[0,0]=9999
alt_a[1,1]=888

In [319]:
alt_a

array([[9999,    1],
       [   9,  888],
       [   0,    3]])

In [323]:
a # oluşturulan alt kümedeki yapılan değişiklikler ana arrayin elemanlarını değiştirdi

array([[9999,    1,    1,    8,    4],
       [   9,  888,    9,    8,    1],
       [   0,    3,    1,    1,    9],
       [   0,    6,    0,    2,    9],
       [   5,    1,    9,    6,    2]])

In [325]:
m= np.random.randint(10,size=(5,5))

In [327]:
m

array([[3, 9, 4, 5, 6],
       [1, 6, 9, 5, 5],
       [2, 7, 6, 7, 5],
       [4, 0, 0, 4, 6],
       [8, 6, 6, 5, 1]])

In [333]:
alt_b=m[0:3,0:2].copy()
alt_b

array([[3, 9],
       [1, 6],
       [2, 7]])

In [337]:
alt_b[0,0]=9999

In [339]:
alt_b

array([[9999,    9],
       [   1,    6],
       [   2,    7]])

In [341]:
m

array([[3, 9, 4, 5, 6],
       [1, 6, 9, 5, 5],
       [2, 7, 6, 7, 5],
       [4, 0, 0, 4, 6],
       [8, 6, 6, 5, 1]])

# Fancy Index ile Elemanlara Erişmek

In [347]:
v = np.arange(0,30,3)

In [349]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [351]:
# indexlerine göre normalde çağıra biliyorum

In [353]:
v[0]

0

In [363]:
v[3]

9

In [357]:
v[5]

15

In [359]:
# hatta indexlerine göre yeni bir liste bile oluşturabiliyorum

In [365]:
[v[0],v[3],v[5]]

[0, 9, 15]

In [367]:
al_getir=[1,3,5]

In [371]:
v[al_getir]

array([ 3,  9, 15])

* bir liste oluşturuyorum "al_getir" ve o listeye işlem yapacağım ana lisntenin index değerlerini giriyorum sonra işlem yapacağım "v" listesinin içerisine oluşturduğum listeyi veriyorum ve sonuç index değerlerini verdiğim elemanlardan oluşan yeni bir liste oluşuyor büyük verilerde çok işe yarayan bir yöntem Fancy Index

In [374]:
m = np.arange(9).reshape(3,3)

In [376]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [378]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [387]:
m[satir,sutun] # çok boyutlu dizilerde bu şekilde indexleri göster sana değerlerini getirsin

array([1, 5])

* Basit indexleme ile fancy index kullanılabilir

In [392]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [394]:
m[0,[1,2]] # m matrixinin 0 indexi ile 1.satır ve 2. sütundaki indexi al

array([1, 2])

* m[0, [1, 2]] ifadesi şunları yapar:
* m[0]: Matrisin 0. satırını seçer.
* Bu, m[0] şu satırı verir: [0, 1, 2].
* [1, 2]: Bu kısım, 0. satırın 1. ve 2. sütunlarındaki elemanları seçer.
* Yani, m[0, [1, 2]], matrisin 0. satırının 1. ve 2. sütunlarındaki elemanları döndürür.
* Eğer m matrisi şu şekilde ise:
* m = [[0, 1, 2],
     [3, 4, 5],
     [6, 7, 8]]
* m[0, [1, 2]], bu matristen [1, 2] sonucunu verecektir. Yani 0. satırdaki 1. ve 2. elemanları seçmiş olursun.

In [398]:
# slice ile birlikte fancy Index kullanımı

In [400]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [402]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

* Yani, m[0:, [1, 2]] şu işlemi yapar:
* Sıfırıcı 0. satırdan başlayarak tüm satırları al (yani matrisin tamamını).
* Her satırdan 1. ve 2. sütunlardaki elemanları seç.

# KOŞULLU ELEMAN İŞLEMLERİ

In [412]:
v = np.array([1,2,3,4,5])

In [424]:
v < 3 # v vektöründeki şarta uyanları göster 

array([ True,  True, False, False, False])

In [426]:
a=v[v<3] # a değişkenine şarta uyanları atama yap

In [420]:
a

array([1, 2])

In [428]:
v[a] # v vektörünün a indexlerine göre değerlerini getir

array([2, 3])

In [436]:
v

array([1, 2, 3, 4, 5])

In [438]:
v[v>=3]

array([3, 4, 5])

In [440]:
v[v<=3]

array([1, 2, 3])

In [442]:
v[v==3]

array([3])

In [444]:
v[v!=3]

array([1, 2, 4, 5])

In [446]:
v

array([1, 2, 3, 4, 5])

In [448]:
v*2

array([ 2,  4,  6,  8, 10])

In [450]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [452]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [454]:
v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel  İşlemler

In [457]:
v=np.array([1,2,3,4,5])

In [459]:
v-1

array([0, 1, 2, 3, 4])

In [461]:
v*5

array([ 5, 10, 15, 20, 25])

In [463]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [465]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [467]:
# ufunc mekanizması operatörler aracılığı ile çeşitli fonksiyonların çalışması söz konusudur

# NumPy ile iki Bilinmeyenli Denklem Çözümü

- 5*x0+x1=12
- x0+3*x1=10

In [476]:
a = np.array([[5,1],[1,3]]) # iki bilinmeyenli denklemde katsayıları birarray yapıyoruz
b = np.array([12,10])  #değerleri ayrı bir array yapyoruz

In [478]:
a

array([[5, 1],
       [1, 3]])

In [480]:
b

array([12, 10])

In [484]:
x=np.linalg.solve(a,b) # fonksiyona tanımlamış olduğumuz arrayleri parametre olarak geçiyoruz
x

array([1.85714286, 2.71428571])