# PANDAS

## Pandas Serisi Oluşturmak

In [3]:
import pandas as pd

In [5]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
# pandas arrayleri değerleri indexleri ile beraber tutar

In [9]:
seri= pd.Series([10,88,3,4,5])

In [11]:
type(seri)

pandas.core.series.Series

In [15]:
seri.axes #Serinin index bilgilerine ulaşılıyor 0 dan 5 e kadar 1er 1er artarak

[RangeIndex(start=0, stop=5, step=1)]

In [17]:
seri.dtype

dtype('int64')

In [19]:
seri.size

5

In [21]:
seri.ndim

1

In [23]:
seri.values

array([10, 88,  3,  4,  5], dtype=int64)

In [27]:
seri.head(3) # serinin başından itibaren 3 eleman getir

0    10
1    88
2     3
dtype: int64

In [31]:
seri.tail(3) # serinin sonundan başlayarak 3 elaman getir

2    3
3    4
4    5
dtype: int64

In [33]:
# index isimlendirme

In [35]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [37]:
pd.Series([99,22,332,94,5],index=[1,3,5,7,9]) # indexleri manuel olarak atadım

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [45]:
seri=pd.Series([99,22,332,94,5],index=["a","b","c","d","e"])

In [47]:
seri["a"]

99

In [49]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

## Sözlük üzerinden liste oluşturmak

In [ ]:
sozluk=pd.Series({"reg":10,"log":11,"cart":12})

In [64]:
seri=pd.Series(sozluk)

In [66]:
seri

reg     10
log     11
cart    12
dtype: int64

In [68]:
# iki seriyi birleştirerek bir seri oluşturma

In [70]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman İşlemleri

In [73]:
import numpy as np

In [75]:
a= np.array([1,2,33,444,75])

In [77]:
seri=pd.Series(a)

In [79]:
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [81]:
seri[0]

1

In [83]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [85]:
seri = pd.Series([121,200,150,99],index=["reg","loj","cart","rf"])

In [87]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [89]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [101]:
list(seri.values)

[121, 200, 150, 99]

In [105]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [107]:
"reg" in seri

True

In [111]:
121 in seri.values

True

In [113]:
# fancy eleman

In [121]:
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [123]:
seri["reg"]=130

In [125]:
seri

reg     130
loj     200
cart    150
rf       99
dtype: int64

In [129]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

In [131]:
# PANDAS DATAFRAME OLUŞTURMA

In [133]:
 l= [1,2,39,67,90]

In [135]:
l

[1, 2, 39, 67, 90]

In [141]:
import numpy as np
m= np.arange(1,10).reshape((3,3))

In [143]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
pd.DataFrame(m,columns=["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [151]:
# df isimlendirme

In [153]:
df=pd.DataFrame(m,columns=["var1","var2","var3"])

In [157]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [159]:
df.columns=("deg1","deg2","deg3")

In [161]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [163]:
type(df)

pandas.core.frame.DataFrame

In [165]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [167]:
df.shape

(3, 3)

In [169]:
df.ndim

2

In [171]:
df.size

9

In [175]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [181]:
type(df.values)

numpy.ndarray

In [183]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [189]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [193]:
a=np.array([1,2,3,4,5])
pd.DataFrame(a,columns=["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# ELEMAN İŞLEMLERİ

In [202]:
import numpy as np

In [204]:
s1=np.random.randint(10,size=5)
s2=np.random.randint(10,size=5)
s3=np.random.randint(10,size=5)

In [206]:
sozluk={"var1":s1,"var2":s2,"var3":s3}

In [208]:
sozluk

{'var1': array([0, 6, 6, 8, 2]),
 'var2': array([9, 9, 8, 5, 2]),
 'var3': array([0, 5, 2, 9, 3])}

In [212]:
df=pd.DataFrame(sozluk)

In [214]:
df

var1  var2  var3
0     0     9     0
1     6     9     5
2     6     8     2
3     8     5     9
4     2     2     3

In [216]:
df[0:1]

var1  var2  var3
0     0     9     0

In [225]:
df.index= ["a","b","c","d","e"]

In [227]:
df

var1  var2  var3
a     0     9     0
b     6     9     5
c     6     8     2
d     8     5     9
e     2     2     3

In [229]:
df["c":"e"]

var1  var2  var3
c     6     8     2
d     8     5     9
e     2     2     3

In [231]:
df.drop("a",axis = 0)

var1  var2  var3
b     6     9     5
c     6     8     2
d     8     5     9
e     2     2     3

In [233]:
df

var1  var2  var3
a     0     9     0
b     6     9     5
c     6     8     2
d     8     5     9
e     2     2     3

* axis satırı ve sütunu ifade etmek için kullanılırken inplace=True kalıcı silme olayını gerçekleştiriyor 

In [245]:
df.drop("b",axis=0,inplace=True)

In [237]:
df

var1  var2  var3
b     6     9     5
c     6     8     2
d     8     5     9
e     2     2     3

In [250]:
df=pd.DataFrame(sozluk)

In [254]:
df

var1  var2  var3
0     0     9     0
1     6     9     5
2     6     8     2
3     8     5     9
4     2     2     3

In [258]:
df.index=("a","b","c","d","e")

In [260]:
l=["c","d","e"]

In [262]:
df.drop(l,axis=0)

var1  var2  var3
a     0     9     0
b     6     9     5

In [264]:
# degiskenler için

In [266]:
"var1" in df

True

In [268]:
l=["var1","var4","var2"]

In [270]:
for i in l:
    print(i in df)

True
False
True


In [272]:
#değişkenler bazında yani sütun bazında yapılan manipulasyon

In [274]:
df

var1  var2  var3
a     0     9     0
b     6     9     5
c     6     8     2
d     8     5     9
e     2     2     3

In [278]:
df["var4"]=df["var1"]/df["var2"]

In [280]:
df

var1  var2  var3      var4
a     0     9     0  0.000000
b     6     9     5  0.666667
c     6     8     2  0.750000
d     8     5     9  1.600000
e     2     2     3  1.000000

In [282]:
df.drop("var4",axis=1,inplace= True)

In [284]:
df

var1  var2  var3
a     0     9     0
b     6     9     5
c     6     8     2
d     8     5     9
e     2     2     3